apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cp4ba-operator-group
spec:
  targetNamespaces:
  - cp4ba
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-cp4a-operator
  labels:
    operators.coreos.com/ibm-cp4a-operator.cp4ba: ''
spec:
  channel: v21.1
  installPlanApproval: Automatic
  name: ibm-cp4a-operator
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
